---
title: "Page2"
author: "Emma Siegfried"
date: "March 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Library
```{r, message=FALSE}

library(tidyverse)

```


Data
```{r, message=FALSE}

df2015 <- read_csv("C:/Users/ensie/Box Sync/UCSB/Winter 2018/ESM 244/Shiny/2015.csv")
df2016 <- read_csv("C:/Users/ensie/Box Sync/UCSB/Winter 2018/ESM 244/Shiny/2016.csv")
df2017 <- read_csv("C:/Users/ensie/Box Sync/UCSB/Winter 2018/ESM 244/Shiny/2017.csv")

```

Wrangle
```{r}

happy15 <- df2015 %>% 
  select("Region", "Rank", "GDP", "Health", "Trust", "Generosity")

happy16 <- df2016 %>% 
  select("Region", "Rank", "GDP", "Health", "Trust", "Generosity")

happy17 <- df2017 %>% 
  select("Region", "Rank", "GDP", "Health", "Trust", "Generosity")

Year15 <- rep(2015, length(happy15$Region))
Year16 <- rep(2016, length(happy16$Region))
Year17 <- rep(2017, length(happy17$Country))

happy15$Year <- Year15
happy16$Year <- Year16
happy17$Year <- Year17

happy_all <- rbind(happy15, happy16, happy17)

happy_1516 <- rbind(happy15, happy16)


```



```{r}

mini <- head(happy_all)

ggplot(data = mini, aes(x=Country, y=Trust))+
  geom_bar(stat="identity", position = position_dodge())

ggplot(happy_1516, aes(x=Health, y=Generosity))+
  geom_point(aes(size = Rank, color = Region), alpha = 0.5)+
  theme_classic()



```


























